2025-02-09 17:19:17,804 - ERROR - Could not retrieve depth information or bids/asks are empty.
2025-02-09 17:19:21,369 - ERROR - Binance API exception: APIError(code=-2015): Invalid API-key, IP, or permissions for action.
2025-02-09 17:19:21,371 - ERROR - Error in run: cannot access local variable 'quantity' where it is not associated with a value
2025-02-09 17:19:21,510 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-4' coro=<ThreadedApiManager.start_listener() done, defined at C:\Python312\Lib\site-packages\binance\threaded_stream.py:44> exception=AttributeError("'ClientConnection' object has no attribute 'fail_connection'")>
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\binance\threaded_stream.py", line 45, in start_listener
    async with socket as s:
  File "C:\Python312\Lib\site-packages\binance\streams.py", line 75, in __aexit__
    self.ws.fail_connection()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'fail_connection'
2025-02-09 17:19:22,092 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-3' coro=<ThreadedApiManager.start_listener() done, defined at C:\Python312\Lib\site-packages\binance\threaded_stream.py:44> exception=AttributeError("'ClientConnection' object has no attribute 'fail_connection'")>
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\binance\threaded_stream.py", line 45, in start_listener
    async with socket as s:
  File "C:\Python312\Lib\site-packages\binance\streams.py", line 75, in __aexit__
    self.ws.fail_connection()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'fail_connection'
